# LambdaTest Configuration

# Project and folder configuration
project_id: "01KTKJ6XWN1ZW9HPWTJ6MNGD3T"
folder_id: "01KTKMM3QHVTVJRYNF9780G2DQ"

# Test Run configuration
assignee: 41319
environment_id: 266986

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"